# Generated by Django 3.2 on 2022-02-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lookAfterMe',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
